export type { BoxCorners, RectLike } from './box'
export * as box from './box'
export type { DOMMatrixLike } from './dom'
export * as domMatrix from './dom'
export type { MatrixDecomposition } from './matrix'
export * as mat from './matrix'
export { approxEqual, clamp, EPSILON, roundTo } from './numeric'
export type { Box, Matrix, Vec2 } from './types'
export * as vec from './vec2'
